FROM docker.elastic.co/elasticsearch/elasticsearch:7.0.0
FROM debian:jessie
FROM java:8-jre


# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
# https://packages.elasticsearch.org/GPG-KEY-elasticsearch
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
RUN apt-get install apt-transport-https

ENV ELASTICSEARCH_MAJOR 7.0
ENV ELASTICSEARCH_VERSION 7.0.0
ENV ELASTICSEARCH_REPO_BASE https://github.com/elastic/elasticsearch.git

RUN echo "deb $ELASTICSEARCH_REPO_BASE stable main" > /etc/apt/sources.list.d/elasticsearch.list

RUN set -x \
	&& apt-get update \
	&& apt-get install apt-transport-https \
	&& apt-get install -y --no-install-recommends elasticsearch=$ELASTICSEARCH_VERSION \
	&& rm -rf /var/lib/apt/lists/*

ENV PATH /usr/share/elasticsearch/bin:$PATH

WORKDIR /usr/share/elasticsearch

RUN set -ex \
	&& for path in \
		./data \
		./logs \
		./config \
		./config/scripts \
	; do \
		mkdir -p "$path"; \
		chown -R elasticsearch:elasticsearch "$path"; \
	done

COPY config ./config

COPY docker-entrypoint.sh /

EXPOSE 9200 9300

RUN chmod -R og+w /usr/share/elasticsearch
USER 1000

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["elasticsearch"]
